### ISSUE TITLE
New Update Spam In-Game, but No New Version Available

### ISSUE THREAD

**Issue by GlitchTeo** [DeadlyBossMods/DeadlyBossMods#452]
I keep getting a message in-game that there's a new version available, that I need to download, even though there isn't one when I check the download page.

**Comment by MysticalOS** [comment]
Double check that you don't havev more than one copy of wow, because you could be up to date on one addons folder but not a separate one for a different wow copy

**Comment by GlitchTeo** [comment]
Good point, but I've never had more than one installation. Could it be that
the addon is checking against alpha releases or something?

Den ons 23 dec. 2020 23:53Adam <notifications@github.com> skrev:

**Comment by QartemisT** [comment]
I think it's more along the lines of say ptr or classic vs retail

**Comment by GlitchTeo** [comment]
Yeah that would make sense, but I don't have neither PTR or Retail
installed. The one time I installed Retail, I didn't install any addons for
it. I can double check that there isn't any other kind of residue though.

Den tors 24 dec. 2020 12:01QartemisT <notifications@github.com> skrev:

**Comment by uncabrian** [comment]
Update is only 2 hours old and still show as outdated in game.

**Comment by MysticalOS** [comment]
Technically a new release went out in last 5 minutes, but I doubt that's what you're talking about.

I really need a screen shot of the notice you guys are seeing to see if it's even the DBM-Core update message or just some hotfix message for specific enounters, which you may be seeing just to notify you the mod is broken and fixed in an upcoming update, any time you wipe to x boss.

Also, as said a bunch of times, if it is a core out of date message the number one cause is a different addons folder than one you've been updating. You'd be surprised how often users have like 2-3 copies of wow installed by complete accident. maybe they updated windows, or moved it to a new drive, and launcher didn't know it so it just installed a new copy instead of finding old one. Meanwhile curse or whatever client kept updating addons for the OLD folder type deal.

**Comment by uncabrian** [comment]
To DBM team,

You were right about the age of update , it said 2 minutes old, not 2 hours. But on WOW addons UI it still showed up as out of date. I had to enable (Load outdated addons) to use DBM Core download which was only 2 minutes old. Is there some code missing that could cause it to show as outdated in WOW interface? DBM seems to be working well, at least so far. But I don't like having to use the option (Load outdated addons). Interface showing DBM as outdated is part of WOW interface setting under Addons. I do love your addons though so keep up the great work.

                                                                  Have a happy new year, Brian Merlin

________________________________

**Comment by MysticalOS** [comment]
if it says out of date I'm still 100% sure youo are NOT updating the right addons folder. You have more than one interface folder, I'd bet on it.
